USE ROLE ACCOUNTADMIN;


-- ===========================================
-- Warehouse and Database Access
-- ===========================================

-- Grant permission to use and operate the warehouse
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE AIRFLOW_ROLE;

-- Grant usage on the database
GRANT USAGE ON DATABASE HAI_DATABASE TO ROLE AIRFLOW_ROLE;


-- ===========================================
-- RAW Schema Permissions
-- ===========================================

-- Grant usage on RAW schema
GRANT USAGE ON SCHEMA HAI_DATABASE.RAW TO ROLE AIRFLOW_ROLE;

-- Grant SELECT on the main raw table
GRANT SELECT ON TABLE HAI_DATABASE.RAW.HAI_DATA TO ROLE AIRFLOW_ROLE;


-- ===========================================
-- INTERMEDIATE Schema Permissions
-- ===========================================

-- Grant usage on INTERMEDIATE schema
GRANT USAGE ON SCHEMA HAI_DATABASE.INTERMEDIATE TO ROLE AIRFLOW_ROLE;

-- Grant ability to create tables and views in INTERMEDIATE schema
GRANT CREATE TABLE ON SCHEMA HAI_DATABASE.INTERMEDIATE TO ROLE AIRFLOW_ROLE;
GRANT CREATE VIEW ON SCHEMA HAI_DATABASE.INTERMEDIATE TO ROLE AIRFLOW_ROLE;

-- Grant SELECT on views in INTERMEDIATE schema
GRANT SELECT ON VIEW HAI_DATABASE.INTERMEDIATE.INT_HAI_DATA_FILTERED TO ROLE AIRFLOW_ROLE;
GRANT SELECT ON VIEW HAI_DATABASE.INTERMEDIATE.INT_HAI_DATA_ENRICHED TO ROLE AIRFLOW_ROLE;


-- ===========================================
-- ANALYTICS Schema Permissions
-- ===========================================

-- Grant usage on ANALYTICS schema
GRANT USAGE ON SCHEMA HAI_DATABASE.ANALYTICS TO ROLE AIRFLOW_ROLE;

-- Grant ability to create tables and views in ANALYTICS schema
GRANT CREATE TABLE ON SCHEMA HAI_DATABASE.ANALYTICS TO ROLE AIRFLOW_ROLE;
GRANT CREATE VIEW ON SCHEMA HAI_DATABASE.ANALYTICS TO ROLE AIRFLOW_ROLE;

-- Grant SELECT on reporting views in ANALYTICS
GRANT SELECT ON VIEW HAI_DATABASE.ANALYTICS.CLABSI_BY_ZIP TO ROLE AIRFLOW_ROLE;
GRANT SELECT ON VIEW HAI_DATABASE.ANALYTICS.CLABSI_BY_STATE TO ROLE AIRFLOW_ROLE;
GRANT SELECT ON VIEW HAI_DATABASE.ANALYTICS.CAUTI_BY_ZIP TO ROLE AIRFLOW_ROLE;
GRANT SELECT ON VIEW HAI_DATABASE.ANALYTICS.CAUTI_BY_STATE TO ROLE AIRFLOW_ROLE;
GRANT SELECT ON VIEW HAI_DATABASE.ANALYTICS.COMBINED_SIR_BY_ZIP TO ROLE AIRFLOW_ROLE;